direction: right

vars: {
  d2-config: {
    layout-engine: elk
    theme-id: 105
    dark-theme-id: 105

    dark-theme-overrides: {
      B1: "#a87410"
    }
  }
}

style: {
  fill: transparent
}

user: " " {
  shape: circle
}

managerNode: "Central server" {
  cli: CLI
  api: Web API
  manager: Manager

  api -> manager
  cli -> manager
}


target1: "Node 1" {
  agent: "Agent" {
    plugin1: Plugin 1
    plugin2: Plugin 2
  }
}

target2: "Node 2" {
  agent: "Agent" {
    plugin1: Plugin 1
  }
}

target3: "Node 3" {
  agent: "Agent" {
    plugin1: Plugin 1
    plugin2: Plugin 2
    plugin3: Plugin 3
  }
}

user -> managerNode.api: "HTTP" { style.fill: "#ffffff"}
managerNode.manager <-> target1.agent: bidirectional\ngRPC (mTLS)  { style.fill: "#ffffff"}
managerNode.manager <-> target2.agent: bidirectional\ngRPC (mTLS)  { style.fill: "#ffffff"}
managerNode.manager <-> target3.agent: bidirectional\ngRPC (mTLS)  { style.fill: "#ffffff"}
